### ISSUE TITLE
molecule always reports docker based hostnames as localhost

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#1524]
# Issue Type

- Bug report

# Molecule and Ansible details

```
molecule, version 2.19.0
```

Molecule installation method (one of):

- pip

# Desired Behavior

Be able to see a meaningful hostname in the output, so you would figure out on what platform you got a failure.

# Actual Behaviour (Bug report only)

```
--> Scenario: 'default'
--> Action: 'destroy'

    PLAY [Destroy] *****************************************************************

    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
```

All steps report "localhost", even when `hostname` is mentioned in platform definition. In fact I would argue that the `platform.name` should be the default value used for hostname, in order to avoid haiving to write something like:
```
platforms:
  - name: centos-7
    hostname: centos-7
    image: centos:7
  - name: fedora-28
    hostname: fedora-28
    image: fedora:28
```

**Comment by dj-wasabi** [comment]
Isn't this because the `create.yml` has a `connection: local` option configured, so each task is executed on the `localhost` and not on the `centos-7` or `fedora-28` host? This is Ansible specific, not Molecule.

**Comment by ssbarnea** [comment]
Ok, lets not close it and move it to ansible. We need to find a way to make the UX better here because if I cannot distinguish between various platforms the output become close to useless. 

It may be tricky to solve but we need to find a way to do it.

**Comment by wilmardo** [comment]
ssbarnea Yes the task is running on the localhost that is why you see `changed: localhost`. 
You could run molecule with `--debug` to see more output (it adds -vvv to ansible) or specify the amount of v in the molecule.yml:

```yaml
provisioner:
  name: ansible
  options:
    v: true
```

But the `changed: localhost` is only visible in create, destroy, or other stages which run with `connection: local`. Thinks of these stages as preparation for the the converge which is the main test of the role.
The converge playbook runs on the the specified platform and returns the hostnames instead of localhost.

**Comment by AlexisLessard** [comment]
The create and destroy actions are executed on the localhost. You can see the playbook [here](https://github.com/ansible/molecule/blob/master/molecule/provisioner/ansible/playbooks/docker/destroy.yml). So basically, the change is on the localhost, so the hostname reflects. Altough I'm not sure I understand why the item is none. Shouldn't the dictionnary of the molecule instance appear instead of none?

@wilmardo  I tried running the test scenario with the vvv option in molecule.yml. However, I think the verbosity only affects the execution on ansible in the docker containers, because nothing changed in the output, except when gathering the facts of the instance (I don't have anything else in the role, I juste created a dummy...). I don't have any more information on the create or destroy action. In any case, I'm not sure this is a bug. Maybe some tests could be conducted with the docker_container module in ansible to see its behavious outside of molecule, see wether instances are shown or not.

**Comment by wilmardo** [comment]
@AlexisLessard The verbosity in the molecule.yml indeed only effects the tasks executed in the docker containers. To see output of the molecule actions like create and destroy you should add --debug to the molecule command:

`molecule --debug test`
