### ISSUE TITLE
molecule should have a debug strategy similar to ansible

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#1726]
# Issue Type

- Feature request

# Desired Behavior

Following the known behavior of `ANSIBLE_STRATEGY=debug` which starts interactive debugger when a task fails we should implement something similar using `MOLECULE_STRATEGY=debug` which should avoid destroying containers and do a `molecule login` to the right container.

This would allow developerto snoop-in and figure out what was wrong in that container or vm.

**Comment by lwm** [comment]
OK, nice. Can you trigger `ANSIBLE_STRATEGY=debug` via the CLI? Or can it be set by the `ansible.cfg` in some way? I haven't used it before.

I' wondering because, beyond the env var which we should support, where to put this on the CLI and/or to allow for it in the `molecule.yml` (which maybe is not so useful in the end). 

And how will this relate to the `--destroy=never`? In a way, and I know @Shaps was agreeing when we talked about that flag not being very well known and a common issue for newcomers to the tool (e.g "How do I keep the container up after tasks fail?").

So, let's unify a 'my tasks failed and I want to inspect'  solution from this issue?

**Comment by ssbarnea** [comment]
All ansible options from CLI do have ansible.cfg corespondents, they config loaded maps any env variable to an options, quite a nice design. So yes, you can add `strategy=debug` but I do not personally see much use on this because it does trigger the interactive debugger.... and I keep ansible.cfg in source control.

**Comment by asmacdo** [comment]
+1 to this. Going with the ansible way would be ideal, but I would be satisfied with `molecule test --debug-failed` or similar. 

This would be *very* helpful, especially for running molecule tests with travis.
