### ISSUE TITLE
document matrix testing with molecule

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#1872]
I have the following use case where I want to test an ansible role using docker with these 
conditions:

```
- platform: centos-7
  release: master
- platform: fedora-28
  release: master
- platform: centos-7
  release: 1.0
```

Platforms are operating systems, mainly platforms defined in molecule.yml file but `release` is mainly a variable that is passed to the role. As you can see there is no NxM matrix as some options are not supported.

Thre are few questions we need to answer while documenting this use case:
* how to include variables specific to one platform, i suspect that this is using `buildargs` an option that is not documented.
* how to avoid copy/paste of common options between each platform listed on molecule.yml (avoid repetition)
* how to limit molecule execution to a single platform-version -- based on `molecule list` I would assume that molecule terminology would be `instance` but this may even more confusing for people that can have multiple machines/instances used as a normal testing approach (like one instance with one web service and one with a database).

PS. I know that this ticket may spin-off several bugs or feature requests, which is ok. This is why I asked to document a recommended solution for the described use case. In time we could update it based on new molecule features.

**Comment by MarkusTeufelberger** [comment]
I guess one way to do this is to create different scenarios for `release: master` and `release: 1.0` and then just run `molecule test --all`. You would specify your `release` variable(s) in `playbook.yml` or `prepare.yml` depending on your requirements and symlink the remaining files into each scenario folder.

If you only want to run/test `platform: fedora-28 release: master`, that's not possible currently, since the granularity is at the scenario level. You could run/test all `release: master` instances at once though.
