### ISSUE TITLE
`kind` (Kubernetes in Docker) Driver

### ISSUE THREAD

**Issue by fabianvf** [ansible-community/molecule#2043]
# Issue Type

- Feature request

# Desired Behavior

[kind](https://github.com/kubernetes-sigs/kind) is an official tool for standing up local Kubernetes clusters in docker. A `kind` driver for molecule would allow users to easily spin up kubernetes infrastructure to test against. `kind` supports a `yaml` configuration file ([example](https://raw.githubusercontent.com/kubernetes-sigs/kind/master/site/content/docs/user/kind-example-config.yaml)), which could either be embedded in the driver configuration section, or we could allow the user to just provide a path to a valid config file.

Configuration options could include:

| parameter | description |
|---------|-----------------|
| name | The name of the cluster |
| version | The version of kubernetes to deploy |
| nodes | The list of nodes and their roles (equivalent to the same section in the cluster config yaml) |
| images | A list of local docker images to be pulled into the `kind` cluster. May also want a way to specify that they be built |
| config | Path to a config file for advanced `kind` configuration |

**Comment by decentral1se** [comment]
I've no personal experience with this tool but from the last WG meeting chat and taking a look at it again, it seems like a good route for us to discuss for supporting testing Kubernetes based roles with Molecule. This item has been sitting on the agenga since the start and there is surely a need for this.

Question: since this is "in docker", does that mean we might actually have some luck running this on our existing CI configuration as is? That would certainly be a big bonus for maintenance.

I know there have been some grumblings about adding yet again new drivers but until there is concrete action taken on a plugin system or some other way of not taking these drivers into core, I think we should proceed the same as we have.

**Comment by retr0h** [comment]
I'd be interested in discussing this.  I'm not sure Molecule is the right tool to do this, but open to discuss.

**Comment by ssbarnea** [comment]
I am closing this because now anyone can write and publish driver plugins, so molecule itself does not need to be modified to support a new driver.
