### ISSUE TITLE
Report tests results

### ISSUE THREAD

**Issue by gkoudjou** [ansible-community/molecule#2174]
# Issue Type

- Feature request

# Molecule and Ansible details

```ansible 2.7.7
  config file = None
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/vEnv27/lib/python2.7/site-packages/ansible
  executable location = /home/vagrant/vEnv27/bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
molecule, version 2.22rc3

```

Molecule installation method :

any

Ansible installation method (one of):

- pip

# Desired Behavior

I need to display a report of failed test and for each, the reason of failure.
I didn't see any option to do it in molecule. Even in proposed related issues/features.

In my environment, i will be use tox. I found pytest-molecule but it seems to focus only in infra test and not other molecule tests (as idempotence for example).

Will I have missed something ? If no, I think it might be a good improvement. The final goal is to have something like cucumber report in Jenkins but the first step will be to have the tests results generated somewhere.

Thanks

**Comment by seandst** [comment]
In addition to pytest's ability to write out junit xml when running the testinfra tests, ansible has the `junit` callback plugin that can export the results of a playbook run to JUnit xml: https://docs.ansible.com/ansible/latest/plugins/callback/junit.html

I do recommend working with Ansible 2.8 or higher, as the "test_case_prefix" param to the callback plugin is great for only including specific tasks in the output for test reporting.

**Comment by ssbarnea** [comment]
Thre is what I currently use https://github.com/pycontribs/pytest-molecule but that transforms each molecule scenario into a single unit-test.

**Comment by gkoudjou** [comment]
> Thre is what I currently use https://github.com/pycontribs/pytest-molecule but that transforms each molecule scenario into a single unit-test.

Hello,

Thanks for the reply. I tried it but i expected a call to molecule test but it seems that only infra test are take into account. I've created an issue here if you can take a look at https://github.com/pycontribs/pytest-molecule/issues/18



> In addition to pytest's ability to write out junit xml when running the testinfra tests, ansible has the `junit` callback plugin that can export the results of a playbook run to JUnit xml: https://docs.ansible.com/ansible/latest/plugins/callback/junit.html
> 
> I do recommend working with Ansible 2.8 or higher, as the "test_case_prefix" param to the callback plugin is great for only including specific tasks in the output for test reporting.

With give a try to the callback junit plugin.

**Comment by gkoudjou** [comment]
Hi,

I've tested the junit callback and it's working well. I took note of the new option of Ansible 2.8. Thanks.

Will closed the feature request as the main work will be elsewhere than on Ansible.

Thanks again.

**Comment by gkoudjou** [comment]
Hello,

The JUnit report doesn't really finally fit my needs.

Even with that, i'm unable to provide a report per platforms in a synthetic ways. The expected results may look like
centos6;success
centos7;fail;some_details_content (optional)

The JUnit output aggregate the output of all playbooks executed (created.yml, playbook.yml - i'm using docker).

Is there any hint or the possibility of writing some playbooks ?

Thanks again

**Comment by ssbarnea** [comment]
I am afraid that because molecule is mainly an orchestrator we cannot split tests per platform, even if I really wish to do that, especially as I have a big desire to make possible to tell molecule to test a single platform. 

Think that the platforms section in molecule may be used by some people in a different way than testing multiple-platforms. They could use this feature to create sidecar containers or VMs that are needed for the other tests like a docker-registry, a database, a web server.

If this happens, how do I know what defines a testing-platform and what defines a resource used by the testing platform.

@gkoudjou Can you look more into this? If you find a way we can achieve it I will be the first to help merging that new feature.

I am a little bit biased towards finding a way to make it work with pytest-molecule as the current way we use it is: `tox->pytest->pytest-molecule->molecule->ansible->pytest-html`

The final result is still a single html report file with one line for each molecule run but if we can split this into smaller bits even better (so each molecule run would produce multiple items).

**Comment by ssbarnea** [comment]
I will close this because there are already few solutions (pytest and junit callback) and it is very unlikely that we will want to make a reporting tool out of molecule.
That reminds me of the issues pytest-coverage went into due to the decision to include reporting. Now they struggle to take it out.
