### ISSUE TITLE
Improvements for CLI

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2539]
Using this as a placeholder for small improvements made to the command line, so it is easier to use the tool and minimize number of keystrokes needed for achieving common tasks.

# force
Add `-f` alias for `--force`, quite common to force running a step, like prepare

# scenario as argument
Transform scenario from being an option to be an argument, or allow both
```
# before
molecule prepare -s foo
# after
molecule prepare foo
```

This is possible be I do not yet see a use to have more than one action on a single call, which means that following argument can be used to mention scenario to apply to.

# Mention force option when returning skipping
When running on interactive tty (opposed to CI), it could be useful to mention that user can use force option to enforce execution of a prepared host.

**Comment by greg-hellings** [comment]
I would like to be able to specify multiple targets (might make the "scenario as argument" option less viable). E.g. I find myself doing this a lot:

```bash
molecule -c ../path/to/shared.yml destroy -s foo
molecule -c ../path/to/shared.yml lint -s foo
molecule -c ../path/to/shared.yml converge -s foo
```

It would be great if I could, like with "make", do this all at once

```bash
molecule -c ../path/to/shared.yml destroy lint converge -s foo
```

And have it execute them in the order specified.

**Comment by ssbarnea** [comment]
This is what `test` sequence does mainly and btw, if you put config into `REPOROOT/.config/molecule/config.yml` you no longer need to specify it.

Basically you would have to only run `molecule test -s foo`

**Comment by greg-hellings** [comment]
Sometimes "test" just does too much. Yes, I know there's the `--destroy never` option, but saving the resource isn't the only reason I'll iterate on converge. Sometimes I don't want verify/idempotence/side_effect to be running, and just want to iterate on converge until the process is running as expected.

And as for the global config, while that is good to know it's not applicable in my case. Each collection I work on (two of my personal and at least one for $DAY_JOB) has a different base configuration that's used in their CI pipeline. Since it's always stored at the same location across all of them I use a Bash alias, but the point still stands.

Less controversial and probably easier to tackle: "-h" as a shortcut for "--help" would also be nice.

**Comment by ssbarnea** [comment]
I am going to close this ticket because it too broad and not directly actionable. Still, anyone is welcomed to raise PRs to improve the CLI and reference this ticket.
