### ISSUE TITLE
yum-based test images should use Python 3 by default

### ISSUE THREAD

**Issue by brianhelba** [ansible-community/molecule#2587]
Currently, any image with `dnf` (the replacement for `yum`) will use Python 3, which primarily covers CentOS 8. Currently, images with only `yum` will use Python 2, which primarily covers CentOS 7.

Following #2577 and the fact that Python 2 is End of Life, test images using `yum` should use Python 3 by default. If it's not acceptable to make this change now, then the change should be made when Molecule formally drops support for Python 2.

The change can be accomplished by running:
```
yum install -y /usr/bin/python3 /usr/bin/python3-config sudo yum-plugin-ovl bash iproute
```
instead of
```
yum install -y /usr/bin/python /usr/bin/python2-config sudo yum-plugin-ovl bash iproute
```
[in `molecule/data/Dockerfile.j2`](https://github.com/ansible-community/molecule/blob/eef9a5fd1758d2e30398a81e9a1cd47d54bc6c2a/molecule/data/Dockerfile.j2#L19), `molecule/test/resources/playbooks/docker/Dockerfile.j2`, and `molecule/test/resources/playbooks/podman/Dockerfile.j2`.

**Comment by ssbarnea** [comment]
This is by design in order to keep using py27 on old systems like CentOS-7 (which do not have dnf). 

At this moment there are no plans to change that, but if latest version of centos-7 will have native centos-3 support with libselinux, we could do it, and also drop support for python2.7 everywhere.
