### ISSUE TITLE
molecule should support current and 2 previous versions of ansible

### ISSUE THREAD

**Issue by richm** [ansible-community/molecule#2599]
# Issue Type

- Feature request

# Molecule and Ansible details

all

Molecule installation method (one of):

all

Ansible installation method (one of):

all

# Desired Behavior

molecule should support the currently released, supported version of ansible plus the last two versions.  For example, molecule v3 only supports ansible 2.9 and ansible 2.8 - it should support ansible 2.7.  In general, molecule should support ansible version N, N-1, and N-2

**Comment by ssbarnea** [comment]
This will not happen, in fact there is a chance that we may even support only one version in the future. Read https://github.com/ansible-community/molecule/pull/2487 for details.

Keep in mind that molecule is 100% community maintained with zero headcount allocated on it. 

Lowering support-matrix was needed in order to make maintenance possible.
