### ISSUE TITLE
lint: documentation possible improvement

### ISSUE THREAD

**Issue by apatard** [ansible-community/molecule#2600]
The documentation of molecule 3.0 gives an example on how to write the lint: section of the molecule file:
```lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
```
This version is not 100% equivalent of what was done with molecule 2.0 for flake8. It was more something like:
```
flake8 molecule/*/tests/*.py
```

Found out this issue in my Gitlab CI tests. I'm using virtualenv and following their documentation, it's inside the project directory. The result was that flake8 was trying to lint files inside the virtualenv directory. Annoying.

Maybe add something about it in the documentation ?

**Comment by ssbarnea** [comment]
https://github.com/ansible-community/molecule/issues/2293 should explain why we did this change. 

I will close this bug because the change in behavior was documented and because there is no single solution for simulating the old linting logic, it depends on lots of factors.

For example, your example may be good for testinfra scenarios, but not for others.
