### ISSUE TITLE
Deprecation checking by molecule

### ISSUE THREAD

**Issue by rsguhr** [ansible-community/molecule#2619]
# Issue Type

- Feature request

# Desired Behavior

It would be great if molecule could check for deprecations. Often with new releases of Ansible something is announced to be deprecated. A few releases later they remove the deprecated part completely.

Ansible (and also molecule) shows a warning message on stderr if something deprecated is used e.g.:
```
- include: "setup-{{ ansible_os_family }}.yml"
  static: no
```
```
$ molecule syntax
 --> Validating schema xxx/molecule/default/molecule.yml.
 Validation completed successfully.
 --> Test matrix
     
 └── default
     └── syntax
     
 --> Scenario: 'default'
 --> Action: 'syntax'
 [DEPRECATION WARNING]: The use of 'static' has been deprecated. Use
 'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion.
 This feature will be removed in version 2.12. Deprecation warnings can be
 disabled by setting deprecation_warnings=False in ansible.cfg.
     
     playbook: xxx/molecule/default/playbook.yml
```

Currently I use following method to check for deprecations:
```
deprecation:
  stage: meta
  script:
    - molecule syntax > /dev/null 2> deprecation_warnings
    - if [ -s deprecation_warnings ]; then cat deprecation_warnings && exit 1 ; fi
```
(a grep for `[DEPRECATION WARNING]` would be better because the ansible-devel version outputs always something on stderr)

**Comment by ssbarnea** [comment]
This is not possible because Ansible does not allow it and I bet you will easily find at least one ticket when I asked for something like this.

I honestly do not want to implement any ansible stdout processing in molecule itself, mainly because output differs based on ansible configuration.

I totally agree with you that we need a way to process deprecations and transform *some* of them into errors, but I am afraid we need some help from ansible team.

There is also another approach which I am considering: doing this processing in pytest-molecule as the tool is already capturing the output of molecule. Still, I am aware that most people are not calling molecule using it.

Lets engage with Ansible core team on finding a solution for this, maybe starting on `#ansible-devel`.

**Comment by ssbarnea** [comment]
This seems to be related to https://github.com/ansible/ansible/pull/58993 but I am going to close this ticket not because we do not want to implement it but because we cannot implement it yet.

I will be more than happy to see this implemented.
