### ISSUE TITLE
Missing cookiecutter template option for init

### ISSUE THREAD

**Issue by kevingentile** [ansible-community/molecule#2657]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.9.6
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]
molecule 3.0.4.dev4+g21ce2f4d
   ansible==2.9.6 python==3.8
```

Molecule installation method (one of):

- source

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

I'm attempting to create my own cookiecutter template to configure new roles. Ansible Galaxy provides users with a [role skeleton](https://docs.ansible.com/ansible/2.7/reference_appendices/galaxy.html#using-a-custom-role-skeleton). I am now attempting to further configure the molecule generated files.
 
I expected to be able to pass my custom cookiecutter configuration to molecule either through a flag or an environment variable.

# Actual Behaviour
The documentation for `molecule init scenario` [mentions a local cookiecutter template](https://github.com/ansible-community/molecule/blob/1563796089710b3e0505acb3ec8f57ba80834c45/molecule/command/init/scenario.py#L57). The scenario command [does a lookup for "driver_template" as a command argument](https://github.com/ansible-community/molecule/blob/1563796089710b3e0505acb3ec8f57ba80834c45/molecule/command/init/scenario.py#L92) but this value doesn't appear to ever be set in the project. Molecule then defaults to the local ([project owned](https://github.com/ansible-community/molecule/tree/master/molecule/cookiecutter)) cookiecutter template.

This appears to have been addressed in #2117. Am I missing something?

**Comment by nikParasyr** [comment]
Hi,

I think the functionality of this was removed with: https://github.com/ansible-community/molecule/pull/2642

I think that the idea is that if you have a cookiecutter template you can directly use it to create it your role layout, instead of using ` molecule init role/scenario`

**Comment by kevingentile** [comment]
@nikParasyr thanks for the link. 

I see how introducing cookicutter would add additional complexity to the project. 
However, given that it _is_ still a part of the project, would it make more sense to remove this feature with the remaining cookiecutter integration(s)?

**Comment by nikParasyr** [comment]
@kevingentile i'm probably not the right person to "answer"/"decide" whether this should (or should not) be part of molecule but this is my **personal opinion** on this given these 2 points:
- molecule had and still has a small/too limited number of active/"constant" contributors
- adding support for a non-default cookiecutter template can add extra complexity

---

> However, given that it is still a part of the project, would it make more sense to remove this feature with the remaining cookiecutter integration(s)?

1. Documentation/cli output should be updated to reflect the current situation. Since 3.0.3 custom cookiecutter templates are  not supported and therefore it should be clear that this is no longer supported 
2. Cookiecutter is used to create a "sane" skeleton for ansible and molecule. Therefore completely removing cookiecutter is an overkill IMO. The question is can we, [**as a community**](https://github.com/ansible-community/molecule/issues/2681), support and maintain custom templates???
For me, since `2.15` it was easy to maintain a custom cookiecutter template to init roles and scenarios that were beyond the default ones. I did not use the cli option for a custom template, i just directly used cookiecutter for the init part. IMHO the init part for roles/scenarios should be used to create a sane role/scenario. For more "advanced" use-cases documentation should indicate how to do it 

--- 

this is just my opinion

**Comment by kevingentile** [comment]
Looking at bit more at #2642 this removed the option for custom driver templates. #2665 draft I was able to get the behavior I was looking for, specifically customizing the `cookiecutter/molecule` section of the scenario using the supported drivers. So as opposed to a driver template, here I'm looking for a "molecule template".

**Comment by ssbarnea** [comment]
There are no plans to reinstate the custom template functionality in molecule, mainly because you can always create your own cookiecutter templates that do not rely on molecule itself.
