### ISSUE TITLE
Molecule should open a Open Collective for sustainability purposes

### ISSUE THREAD

**Issue by decentral1se** [ansible-community/molecule#2681]
# Issue Type

- Justice

# Desired Behavior

Molecule maintainers are supported financially for their volunteer work.

Molecule opens a https://opencollective.com. RedHat support this move for both non-RH staff and RH staff alike to receive compensation for their work. RH itself should donate to this fund to support the community. Commercial companies who make use of Molecule for automation should be asked asked to support the project. The community should have control over how this financial support is put to use. Open Collective tools make this a transparent process which can be monitored.

In practical terms, this means we come together to support @ssbarnea right now, the sole maintainer of this project. This in turns allows them to be more active in community building which they are absolutely capable of doing.

The Open Collective headline is:

> Make your community sustainable
 
Since Molecule is completely community run we need to support that community. We all want a sustainable Molecule. See https://github.com/ansible-community/molecule/pull/2679#issuecomment-621128786 and https://github.com/ansible-community/molecule/pull/2445#issuecomment-561199653 for further background information.

**Comment by gundalow** [comment]
@decentral1se Thank you for creating this issue, and for raising the important points about sustainability and long term maintainability.

What specific things do you think this fund could be used for?

Today Red Hat pays directly for the CI for all of gh/ansible-community. The CI bill for Molecule alone was around $500/month when we used Travis-CI. We (Red Hat) are now paying for Zuul, though we have a general pool of resources, so I don't have a dollar amount for that.

I've hidden the other topics in https://github.com/ansible-community/molecule/pull/2679 as "off topic". As @decentral1se says, this issue is the place for those discussions to take place.

**Comment by gundalow** [comment]
Copied from https://github.com/ansible-community/molecule/pull/2679

@decentral1se Red Hat employees (such as myself and @ssbarnea) can't accept sponsorship for these projects.

Though you (@decentral1se) are welcome to add a GitHub sponsorship link under molecule and its drivers. 
Which we added in https://github.com/ansible-community/molecule/pull/2464, though was removed by yourself in https://github.com/ansible-community/molecule/pull/2481/. I'm happy for you to add yourself back in. (I didn't realise you'd removed yourself till now when I went looking).


Red Hat currently supports Molecule by:
* Providing hosting under the Community GitHub account, which helps promote Molecule
* Paying for CI (details in https://github.com/ansible-community/molecule/issues/2681#issuecomment-621163739)
* providing @ssbarnea (and to a much lesser extend myself) time to work on this as part of their day job

The senior leadership at Ansible are aware that we need people added to this project. Molecule is important to Ansible, though at the moment, Collections is taking up everybody's time. 

I'm happy to chat 1:1 (email, video) with anybody about this, or anything else that's related to the wider Ansible project and its community.

**Comment by decentral1se** [comment]
> What specific things do you think this fund could be used for?

Financial support for maintainers. If time is being made on RH work hours for work on Molecule then good. However, what about the time outside of RH work hours? What about the people not working for RH? Remember that there is more work that goes into this than dedicated source code changes: running meetings, design, consensus building and working with the wider community to receive feedback. All this takes time and makes molecule successful.

> I'm happy for you to add yourself back in. 

Firstly, I won't maintain molecule core again under current circumstances and secondly, adding an individual support is not the goal of this ticket.

> (I didn't realise you'd removed yourself till now when I went looking).

Reason in https://github.com/ansible-community/molecule/pull/2445#issuecomment-556857063.

> Red Hat currently supports Molecule by ...

That's good but off-topic in regard to the specific point I am making on this ticket. There is a lot of person-hours of work to make Molecule succeed. That is not supported. 

To make it clear, the real thing that makes molecule a thriving project is a lot of people working on it. Open Collective is one approach to making that work that rests power directly in the hands of the community members to select help bring more contributors in and compensate them for their work therefore making this a sustainable project to contribute to.

> @decentral1se Red Hat employees (such as myself and @ssbarnea) can't accept sponsorship for these projects. 

Molecule opens a https://opencollective.com. RedHat support this move for only non RH staff ~~both non-RH staff and RH staff alike to receive compensation for their work~~.

So ^^^ is then satisfiable? Why doesn't RH support its own workers in this extra work (here I specifically mean the out-of-hours work)?

> The senior leadership at Ansible are aware that we need people added to this project.

What is the RH position here? That the project is not sustainable and in the future more paid staff will be put on Molecule? I know you know it but for the sake of transparency, we're already waiting 1+ year for more committed human resources here and the project will struggle to stay relevant in the future without more focus.

That is one approach which is so far opaque to those of us not in RH. The other is to allow the community do what it does best and that is at least, what as put on offer when I first turned up on this project.

> I'm happy to chat 1:1 (email, video) with anybody about this, or anything else that's related to the wider Ansible project and its community.

**Comment by ssbarnea** [comment]
Clearly the maintenance of the project is something we need to address. The project requires considerable amount of time and I found support from other contributors, a bit sparse. I saw people asking for help or creating bugs, but less of making pull requests and almost none offering to addressing existing bugs.

I have no idea how these issues are to be addressed but I know that they are not unique to this project, in fact most open-source projects of similar nature (testing tools) have similar issues.

If Open Collective helps to get more people involved with the project, I all for it.

I do have few reservations regarding the "companies ... should be asked to support" part, as I personally have no interest in marketing any services around the tool. Still, if anyone wants to do this, they are more than welcomed. In fact, it may prove to be very useful for the project to document some ways a user could get support. because I already started to ignore lots of questions I see on irc, not because I do not want to help, but because the day is too short.

**Comment by geerlingguy** [comment]
I think this points to the general problem of 'how do you support community open source projects' that affects practically every Open Source project I've ever worked on (Drupal, K8s, Ansible, Molecule, Pi Foundation projects, etc.).

I know it can be slightly more complicated when some maintainers are compensated for their time (and/or choose to donate extra non-compensated time), while others are not, especially if a product leads to lead generation and/or sales for a particular company.

A couple of my previous employers had this exact issue, and the answer is "it's complicated", especially if a project is more of a 'bazaar' and less a 'cathedral' that is owned by one entity.

As someone who has been through trying out Open Collective... Donation buttons, Grants, GitHub Sponsors, Patreon, Gratipay, and BountySource, the answer is still "it's hard", and I'm still trying to figure out what is the best way to find just compensation for open source maintainership. And in the end, none of the above options that I've tried (individually or as part of small orgs) really caught fire except for a very select few who were able to 'go viral' and get a strong base of support, or were already well-known enough that they wouldn't have _needed_ to go that route for funding.

**Comment by decentral1se** [comment]
Thanks for weighing in @geerlingguy.

> I think this points to the general problem

I don't have a general problem in mind, I have a Molecule problem in mind. While I do see the parallels with the greater problem I am not focussed on those. I want this discussion to stay focussed on what will work for Molecule.

> And in the end, none of the above options that I've tried (individually or as part of small orgs) really caught fire

There are plenty of examples where it works effectively and guarantees independant sustainability. Just take a look at https://opencollective.com/discover?show=open%20source. There are projects that fit into the same category as Molecule.

---

If I run it by the numbers as a previous maintainer, I guess this project needs 3 paid-up maintainers working at least 5-10 hours a week (assuming part-time) to make it successful.

Now, the project has had 200 contributors (see https://github.com/ansible-community/molecule/graphs/contributors) but has retained approximately 1 of those as a core committed maintainer. This project has an extremely low rate of contributor retention.

My open collective approach is one way to actually have a fighting chance at contributor retention which meets contributors where they are at, meaning, they can actually justify working on this project due to a form of useful compensation. 

If there are other approaches, let us here them.  I wish RH was committing more paid human resources to this project. That would solve it to have a paid full-time maintainer on this full-time. But that isn't happening and hasn't for some time. It's time for other proposals without a clear commitment from RH.

**Comment by decentral1se** [comment]
Also see https://www.reddit.com/r/ansible/comments/ga9hqa/rfc_molecule_sustainability_discussion/fp1ag3m/.

**Comment by retr0h** [comment]
This is one of the reasons I had reached out to RedHat originally.  As the original author of both v1 and v2 Molecule, I was the only person working on Molecule for many years, taking about it, and trying to get user adoption.

With that said, I would be happy to work with @ssbarnea, and help out again.

**Comment by decentral1se** [comment]
Sooooo, what's the outcome?

**Comment by decentral1se** [comment]
:wave: https://github.com/ansible-community/molecule/issues/2764 :wave:

**Comment by ldarmbuster** [comment]
From what I'm reading, the consensus seems to be in support of accepting donations through Open Collective or a similar platform. That raises the next set of questions:

Red Hat currently provides financial support; are they any possible situations where this support could be pulled?
How do we make sure Red Hat employees are not negatively affected? (because they can't accept sponsorship according to @gundalow)
Who manages the Open Collective account?
Do we need a Treasurer position?
Are we only trying to compensate for time or are there other expenses to keep in mind?
How do we determine how much someone is compensated? (see the comment by @geerlingguy)
