### ISSUE TITLE
Provide a way to add podman arguments

### ISSUE THREAD

**Issue by Yajo** [ansible-community/molecule#2714]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.9.9
  config file = None
  configured module search path = ['/var/home/yajo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/home/yajo/mydevel/mando/.venv/lib64/python3.8/site-packages/ansible
  executable location = /var/home/yajo/mydevel/mando/.venv/bin/ansible
  python version = 3.8.3 (default, May 15 2020, 00:00:00) [GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]
molecule 3.0.4
   ansible==2.9.9 python==3.8
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

As you can see in https://github.com/containers/buildah/issues/2175#issuecomment-639296244, podman needs some specific arguments to be able to run inside a privileged docker container, [which is the executor enabled for free in gitlab.com](https://docs.gitlab.com/ee/user/gitlab_com/#shared-runners).

If I want to use podman to test my roles on https://gitlab.com without needing to use a custom executor, it would be very much easier if I had a way to configure podman args.

Specifically I'd need `--cgroup-manager cgroupfs --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs --storage-driver overlay` in this case, although I guess the possibilities are endless.

**Comment by ssbarnea** [comment]
@Yajo Sure, no doubts about the need of allowing a way to specify extra arguments in a future proof way.

I still do have few questions around the subject:
- Are these arguments driver specific or container specific? Based on this we may know where we need to add them, maybe even at both levels.
- Do you know if podman ansible modules used do allow this or we need the modules to be improved first?

I did assign the ticket to @sshnaidm as he is the podman plugin author and have the best knowledge in that area.

**Comment by Yajo** [comment]
El dom, 7 de jun de 2020 a las 02:32, Sorin Sbarnea 
<notifications@github.com> escribió:
> Are these arguments driver specific or container specific? Based on 
> this we may know where we need to add them, maybe even at both levels.
I think these are driver-specific. In the issue linked above you can 
see that these flags go between `podman` and `run` in the command, 
basically making them podman-wide flags.
> Do you know if podman ansible modules used do allow this or we need 
> the modules to be improved first?
It seems it is supported 
<https://github.com/containers/ansible-podman-collections/blob/80b2ae6abf87ea12c70440e04bfb15a9e76714c8/plugins/modules/podman_container.py#L146-L152> 
(without idempotence, though).

**Comment by sshnaidm** [comment]
> It seems it is supported <https://github.com/containers/ansible-podman-collections/blob/80b2ae6abf87ea12c70440e04bfb15a9e76714c8/plugins/modules/podman_container.py#L146-L152> (without idempotence, though).

[`podman_container`](https://github.com/containers/ansible-podman-collections/blob/master/plugins/modules/podman_container.py)module supports everything podman supports. If it accidentally doesn't, let me know ASAP :)
It'd be much easier to install [Ansible Podman collections ](https://github.com/containers/ansible-podman-collections)and use [`podman_container`](https://github.com/containers/ansible-podman-collections/blob/master/plugins/modules/podman_container.py) from there, also to map all supported options. But I don't think `molecule` supports install of different collections as requirements.
In Ansible 2.10 it will be part of Ansible, so then I think we can use [`podman_container`](https://github.com/containers/ansible-podman-collections/blob/master/plugins/modules/podman_container.py) as is instead of command line.
For now it's not too difficult just to add command line arguments for podman CLI in [`create.yml`](https://github.com/ansible-community/molecule/blob/f31502746f33abd7720264430e4f665be72d3df1/molecule/provisioner/ansible/playbooks/podman/create.yml).

I think also that it's a great use case and has to be documented in Molecule docs. Using `docker` containers in various provided CI systems is very common, and it'll be very helpful to show users how to run podman there.
@Yajo can you please add documentation bits after this functionality will be merged?

**Comment by Yajo** [comment]
Yes, of course.
