### ISSUE TITLE
molecule login ignoring scenario

### ISSUE THREAD

**Issue by Nightreaver** [ansible-community/molecule#2923]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.10.2
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/venv/lib/python3.8/site-packages/ansible
  executable location = /opt/venv/bin/ansible
  python version = 3.8.6 (default, Oct 22 2020, 05:11:53) [GCC 9.3.0]
molecule 3.1.5
    ansible:2.10.2 python:3.8
    azure:0.4 from molecule_azure
    delegated:3.1.5 from molecule
    docker:0.2.4 from molecule_docker
    ec2:0.2 from molecule_ec2
    gce:0.1 from molecule_gce
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

-  yamllint
 - ansible-lint

# Desired Behavior

Usecase: Molecule with couple scenarios, each containing different drivers.  

Running `molecule login --host XXXX` should use default scenario for login/validation
Running `molecule login --host XXXX --scenario my_scenario`  should use only `my_scenario` for login/validation

Ignore other scenarios/folders and associated drivers.

# Actual Behaviour

Running `molecule login --host XXX` gives 

```
ERROR: Failed to pre-validate.

{'driver': [{'name': ['unallowed value vagrant']}]}
```

though `vagrant` driver is not part of the **current/chosen** scenario but one of **another** one contained in molecules folder that is not going to be used.

**Comment by tadeboro** [comment]
Molecule loads and validates all scenario configs before running any command. This is why your login command fails.

There is a historical reason behind this behavior: scenario names did not have to match the directory they lived in. For example, it was perfectly valid to have a `molecule/sample/molecule.yml` file that contained a `scenario: { name: not_sample }` definition. And in this case, Molecule would reference this scenario with the `not_sample` name.

Because scenario name and the containing directory can differ, Molecule must load all configuration files to find the scenario names. And this means that we need to make sure all our scenarios can be loaded even if we only want to execute a single one.

I know we talked about deprecating the scenario name option, but I am not sure if this ended being implemented or not. Maybe @ssbarnea can pitch in here with some information?

If the scenarios must be named the same as the directory that they live in, we may resolve this issue by only loading scenarios that we intend to use. Otherwise, there is not much we can do here.

**Comment by ssbarnea** [comment]
Closing as this is indeed an architecture limitation. You do need to ensure you have all the drivers needed already installed, even if the command you try to run is from another scenario.
