### ISSUE TITLE
molecule does not find `module_utils` of tested ansible role

### ISSUE THREAD

**Issue by ltalirz** [ansible-community/molecule#3045]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
```

ansible 2.10.6
molecule 3.2.3

[See here for CI logs](https://github.com/dokku/ansible-dokku/pull/98/checks?check_run_id=1822645321#step:5:147)

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

When testing an [ansible role that includes a `module_utils` folder](https://github.com/ltalirz/ansible-dokku/tree/issue_88_clone_version), a python module inside this folder (e.g. `dokku_app_utils.py`) should be importable from other ansible modules via:
```python
from ansible.module_utils import dokku_app_utils
```

# Actual Behaviour

[This role](https://github.com/ltalirz/ansible-dokku/tree/issue_88_clone_version) uses a `module_utils` folder to share code between ansible modules it provides.
Running the linked branch directly using ansible 2.10.6 on a server works fine.

When testing the role using molecule, I run into the following error (see  [CI logs](https://github.com/dokku/ansible-dokku/pull/98/checks?check_run_id=1822645321#step:7:684)):
```
fatal: [instance]: FAILED! => {"msg": "Could not find imported module support code for ansible.modules.dokku_clone.  Looked for (['ansible.module_utils.dokku_app_utils.dokku_app_present', 'ansible.module_utils.dokku_app_utils'])"}
```

For some reason that I haven't figured out, the `module_utils` folder is found when running the role directly via ansible, but not found when the role runs via molecule.

I've tried 
 - making the name of the module unique
 - adding `__init__.py`s

but that didn't help (and did not seem likely, since the role runs fine locally).

Any ideas?

P.S. Nice work on the issue template selector! It's a great way to communicate all the available communication channels.

**Comment by ltalirz** [comment]
Oh wait - I just realized that the issue must be specific to the `verify` stage. The python module in question is actually used  (successfully) during `converge`.

**Comment by ltalirz** [comment]
Issue persists with ansible 3.3.0 and molecule[docker] 3.3.0.

**Comment by tadeboro** [comment]
I took a look at this issue and as far as I can tell, Molecule is actually doing too much here, masking the real problem.

When I execute the `molecule --debug verify` command, I see this in the output (I manually split the things across multiple lines for convenience; this is actually a single line):

```
ANSIBLE_LIBRARY:
  /home/tadej/xlab/ansible/tmp/dokku_bot.ansible_dokku/venv/lib64/python3.9/site-packages/molecule/provisioner/ansible/plugins/modules:
  /home/tadej/.cache/molecule/dokku_bot.ansible_dokku/default/library:
  /home/tadej/xlab/ansible/tmp/dokku_bot.ansible_dokku/library:
  /home/tadej/.ansible/plugins/modules:
  /usr/share/ansible/plugins/modules
```

The problematic part is `/home/tadej/xlab/ansible/tmp/dokku_bot.ansible_dokku/library`. If this directory would not be added to the library path, Ansible would error out saying that the module cannot be found. And this is actually what should happen here.

Why? Because this is the error end-users will see if they try to use modules from the `dokku_bot.ansible_dokku` role. Ansible does not expose content from the role to the playbook authors until they actually use the role in their playbook. Once the role has been used at least once, they gain access to plugins and modules from the role.

So, to properly fix this, we would need to remove the https://github.com/ansible-community/molecule/blob/3.3.0/src/molecule/provisioner/ansible.py#L929 from the molecule (this will expose the real error here). The `dokku_bot.dokku_ansible` role needs to "use" itself in the verification playbook before it can start using custom modules.

See https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#embedding-modules-and-plugins-in-roles for more information.

**Comment by ltalirz** [comment]
> Why? Because this is the error end-users will see if they try to use modules from the `dokku_bot.ansible_dokku` role. Ansible does not expose content from the role to the playbook authors until they actually use the role in their playbook.

Thanks a lot for the explanation @tadeboro !

> So, to properly fix this, we would need to remove the https://github.com/ansible-community/molecule/blob/3.3.0/src/molecule/provisioner/ansible.py#L929 from the molecule (this will expose the real error here). 

After reading the ansible docs you linked, I agree that this sounds like the correct behavior. I wonder though whether molecule users in the meanwhile have started to rely on the fact that they *can* use the modules of the role in the verify playbook (as e.g. done [here](https://github.com/dokku/ansible-dokku/blob/4427ea88872c9099f7f7b18fc312879561b5d333/molecule/default/verify.yml#L9-L11) )...

> The `dokku_bot.dokku_ansible` role needs to "use" itself in the verification playbook before it can start using custom modules.

Is there a way for me to avoid re-running the role in `verify.yml` before starting to test modules?
After all, the verification stage runs after the `converge` and `idempotence` stages.

Happy to add a PR to the molecule documentation regarding this if that would be useful.

**Comment by tadeboro** [comment]
> After reading the ansible docs you linked, I agree that this sounds like the correct behavior. I wonder though whether molecule users in the meanwhile have started to rely on the fact that they _can_ use the modules of the role in the verify playbook (as e.g. done [here](https://github.com/dokku/ansible-dokku/blob/4427ea88872c9099f7f7b18fc312879561b5d333/molecule/default/verify.yml#L9-L11) )...

I am almost sure users do (ab)use this feature, so it will have to stay in molecule until we release 4.0.0 that can break backward compatibility. But this "feature" is really bad because it gives role authors a false sense of what works and what does not. So my plan is to remove this from the molecule, but not before Molecule 4.0.0.

> Is there a way for me to avoid re-running the role in `verify.yml` before starting to test modules?
> After all, the verification stage runs after the `converge` and `idempotence` stages, so it would seem like a waste of time to run the role for a third time.

Unfortunately, no. But what you can do is add an empty task file to your role. With this new entry point, you (and your users) will be able to load the role modules and plugins without actually running anything. For example, if you add an empty `init.yml` file to the `tasks` directory, you can do something like this in your `verify.yml` file:

```
- name: Verify
  hosts: all
  become: true

  tasks:
  - name: Load custom content
    include_role:
      name: dokku_bot.ansible_dokku
      tasks_from: init

  # More here
```

This first task will not execute anything (because the `tasks/init.yml` file is empty) while still giving you access to all of the custom plugins and modules.

> Happy to add a PR to the molecule documentation regarding this if that would be useful.

This would indeed be a very welcome addition to the docs. If you manage to come up with something (even just documenting the conversation we had here would be a good progress), feel free to ping me in the PR. And thank you in advance!
