### ISSUE TITLE
Inappropriate return code

### ISSUE THREAD

**Issue by aminvakil** [ansible-community/molecule#3084]
Running `molecule` command without anything should return error code 2, it's right now returning 0.

# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.10.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/amin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
molecule 3.3.0 using python 3.9 
    ansible:2.10.7
    delegated:3.3.0 from molecule
```

Molecule installation method (one of):

- source

Ansible installation method (one of):

- OS package

Detail any linters or test runners used:

# Desired Behavior

Return error code 2

# Actual Behaviour

Returns 0.

P.S.
I've tried finding and opening a PR to fix this unsuccessfully, I'd be more than happy to fix it if I knew how :)

**Comment by tadeboro** [comment]
It seems like the click library that Molecule uses to build its CLI interface does not treat the missing subcommand as an error. I tested the example from https://click.palletsprojects.com/en/7.x/quickstart/#nesting-commands, and that example also terminates with a zero exit code.

I did not find any easy way of telling click to treat missing as an error, so fixing this is not trivial. In an ideal world, we would drop the click library completely because it brings its own set of troubles, but that is also a non-trivial amount of work to perform.

**Comment by ssbarnea** [comment]
I am going to close this because I do not find it critical. What it does without arguments is same as `--help`, so no strong reason to fail.

Note: if someone proposed a fix, i will likely accept it.

**Comment by aminvakil** [comment]
@ssbarnea It's not critical for sure, it's not easy to fix, yes, but the issue has not been fixed yet, right? What's the reason of closing an issue that has not been fixed?

**Comment by ssbarnea** [comment]
Cleaning out the issue tracker is the issue, less open issues makes it easier to track them.

Closed does not mean fixed, it only means that we do not expect activity on it.

Again, if you have time you can write a PR.

Same applies for most wishes or feature requests, they now go into discussions. We were flooded by "ideas" nobody was willing to spend time implementing.
