### ISSUE TITLE
ERROR:Task exception was never retrieved when run molecule test command

### ISSUE THREAD

**Issue by gun082544** [ansible-community/molecule#3112]
When I run molecule test command, I found an error after converge step like this:

![error molecule test](https://user-images.githubusercontent.com/56395331/118108420-2b0ee080-b40a-11eb-9964-9006a938265f.png)

I use Python 3.8, Ansible 2.10.8 and molecule 3.3.0.
How can I fix this error ?
Thank you.

**Comment by ssbarnea** [comment]
That is caused by too much output being logged by Ansible per-line. Recently we increased the default limit from 64kb to 512kb in subproces-tee. Half a megabyte is huge but if you run in verbose it we may need even more.

Bumping this value is easy but I am worried about to which extend we should do it and if there are going to be other undesired side-effects.

@felixfontein @tadeboro What do you think?
