### ISSUE TITLE
Remove the mol command alias

### ISSUE THREAD

**Issue by mperry2** [ansible-community/molecule#3406]
Issue #2737 should be reverted. We should not pollute the path with duplicate executables. This is **_exactly_** what aliases exist for, and users can easily create an alias if they wish to use mol to call molecule.

Maybe add a deprecation warning for one year and then remove it for good after that.

**Comment by mperry2** [comment]
I submitted a PR, but I'm not sure if I put the deprecation in the correct place. I copied the format from what Ansible uses in order to be consistent.

**Comment by ssbarnea** [comment]
As the author of the `mol` feature I have mixed feelings but I will wait for other molecule users to [vote up/down on that proposal](https://github.com/ansible-community/molecule/issues/3406#issue-1109986272) before making a decision.

Removal should not be a problem because is a recent feature and I doubt we have many users using it, especially in production (scripts). Considering that a major version of molecule is already baking I could even backport the deprecation on `3.5.x` and make a small patch, so we could include full removal in upcoming `3.6.0`. Still, i want feedback before acting on it.

**Comment by tadeboro** [comment]
I am +1 on removing the mol alias, but not in the minor release.

**Comment by ssbarnea** [comment]
@tadeboro The idea was to deprecate it in minor release and remove in major. Or you mean that you want to change the versioning pattern on molecule? So far, `3.0`,... `3.5` all counted as major releases, all introducing some breaking changes. Is that your call for `4.0`?

**Comment by tadeboro** [comment]
I was convinced Molecule respects semver, but I guess I was wrong (and lucky that none of the projects I use molecule on broke during the version bumps). I was targeting 4.0 with my comment, but my argument is completely invalid if Molecule breaks things in "minor" releases.

Anyway, I think a deprecation warning should be in place for at least a few months before we can remove the mol entry point.

**Comment by greg-hellings** [comment]
I agree with this proposal in principle. I use several `mol...` aliases and would use one for the full executable if I wanted to shorten it as well.

**Comment by ziegenberg** [comment]
The `mol` command alias was removed in #3457 (and documentation was fixed in #3458). Therefor I guess we can close this issue.
