### ISSUE TITLE
Use of autoescape=True in Jinja template breaks Vagrant

### ISSUE THREAD

**Issue by samiam** [ansible-community/molecule#3912]
# Issue Type

- Bug report

# Molecule and Ansible details

```
molecule 5.0.1 using python 3.11
    ansible 2.14.5
    delegated 5.0.1 from molecule
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

Jinja2 should generate correct Vagrant config files as it did in molecule <= v4.

# Actual Behavior

This line:
https://github.com/ansible-community/molecule/blob/main/src/molecule/util.py#L178
from this [PR](https://github.com/ansible-community/molecule/pull/3887) introduced the regression.

Briefly, quoted strings that used to be output in the Vagrantfile, are now escaped.

```
# v4
c.vm.box_url = "https://some.url.com"

# v5
c.vm.box_url = &#34;https://some.url.com&#34;
```

molecule-vagrant no longer works.

Here's a line from the template that I'm using as an example.  There's plenty more in there.

https://github.com/ansible-community/molecule-vagrant/blob/main/molecule_vagrant/modules/vagrant.py#L222

Here's my PR that adds a simple test of quoted strings in Jinja2 templates:
https://github.com/ansible-community/molecule/pull/3911

# Summary

My ask is that `autoescape` be turned off when rendering templates.

**Comment by apatard** [comment]
I hoped I fixed everything in https://github.com/ansible-community/molecule-plugins/commit/7eab71d0da547914e46a1110c56d4ac949b9bce9. Looks like it's not the case. Can you open a bug on molecule-plugins with:

- a test case
-  the parts of the template missing escaping ?

I'm not sure that disabling auto-escaping in molecule will happen since on general case it's a matter of security, so it's better to fix the template. If/When https://github.com/ansible-community/molecule-plugins/pull/142 is merged, it may be considered to disable auto-escaping since it won't impact molecule.

**Comment by samiam** [comment]
I added a PR with the additional safe filters:
https://github.com/ansible-community/molecule-plugins/pull/153.

Sorry I don't have a test with it.
I'm new to tox and my environment wasn't working.  
I wish there was a little guidance on setting up the tests to run...
Anyway, I'll try to get one written when I can.
It will probably be a little janky; reading the Vagrantfile for certain config statements to ensure they are correct?
